// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pg.Api.Database;

#nullable disable

namespace Pg.Api.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20241014095019_FixedCollationNames")]
    partial class FixedCollationNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:en_ci_as", "en-u-ks-level1,en-u-ks-level1,icu,False")
                .HasAnnotation("Npgsql:CollationDefinition:en_ci_as_like", "en-u-ks-level2,en-u-ks-level2,icu,True")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pg.Api.Database.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .UseCollation("en_ci_as");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("en_ci_as");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The first client",
                            Name = "Client 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The second client",
                            Name = "Client 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is another client",
                            Name = "Another"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
